import Foundation

/// Cloudflare R2 storage service for images (avatars, event covers)
/// Uses pre-signed URLs generated by Supabase Edge Functions to avoid egress costs
actor R2StorageService {
    static let shared = R2StorageService()

    @MainActor private var supabase: SupabaseService { SupabaseService.shared }

    // MARK: - Upload

    func uploadImage(data: Data, path: String, contentType: String = "image/jpeg") async throws -> String {
        // Get pre-signed upload URL from Edge Function
        let response: UploadURLResponse = try await supabase.invokeAuthenticatedFunction(
            "r2-upload-url",
            body: [
                "path": path,
                "content_type": contentType
            ]
        )

        // Upload directly to R2 using pre-signed URL
        var request = URLRequest(url: URL(string: response.uploadUrl)!)
        request.httpMethod = "PUT"
        request.setValue(contentType, forHTTPHeaderField: "Content-Type")
        request.httpBody = data

        let (_, urlResponse) = try await URLSession.shared.data(for: request)
        guard let httpResponse = urlResponse as? HTTPURLResponse,
              (200...299).contains(httpResponse.statusCode) else {
            throw R2Error.uploadFailed
        }

        return response.publicUrl
    }

    func uploadAvatar(data: Data, userId: UUID) async throws -> String {
        let path = "avatars/\(userId.uuidString)/avatar.jpg"
        return try await uploadImage(data: data, path: path)
    }

    func uploadEventCover(data: Data, eventId: UUID) async throws -> String {
        let path = "events/\(eventId.uuidString)/cover.jpg"
        return try await uploadImage(data: data, path: path)
    }

    func uploadGameImage(data: Data, gameId: UUID) async throws -> String {
        let path = "games/\(gameId.uuidString)/image.jpg"
        return try await uploadImage(data: data, path: path)
    }

    // MARK: - Delete

    func deleteImage(path: String) async throws {
        try await supabase.invokeAuthenticatedFunction(
            "r2-delete",
            body: ["path": path]
        )
    }
}

struct UploadURLResponse: Decodable {
    let uploadUrl: String
    let publicUrl: String

    enum CodingKeys: String, CodingKey {
        case uploadUrl = "upload_url"
        case publicUrl = "public_url"
    }
}

enum R2Error: LocalizedError {
    case uploadFailed
    case deleteFailed

    var errorDescription: String? {
        switch self {
        case .uploadFailed: return "Failed to upload image"
        case .deleteFailed: return "Failed to delete image"
        }
    }
}
